version: "2"
services:
  proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /mnt/disks/nginx-data:/data
      - /mnt/disks/letsencrypt:/etc/letsencrypt
