---
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:latest
    hostname: my_foundry_host
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./UserData
        target: /data
    environment:
      FOUNDRY_RELEASE_URL: https://r2.foundryvtt.com/releases/13.344/FoundryVTT-Linux-13.344.zip?verify=1748209157-fidbUhA5xxwFdLstHmZUKWoQUhVMuG0rw%2FmUNe%2BS6u4%3D
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
      