---
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    env_file: .env
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - DB_PORT=3306
      - DB_HOST=bookstack_db
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_DATABASE=${MYSQL_DATABASE}
    volumes:
      # - /bookstack_app_data:/config
      - /mnt/disks/bookstack/bookstack_app_data:/config
    ports:
      - 50001:80
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: mysql:8.3
    env_file: .env
    container_name: bookstack_db
    ports:
      - 3306:3306
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      # - ./bookstack_db_data/mysql:/var/lib/mysql
      # - ./bookstack_db_data/config:/config
      - type: bind
        source: ./mysql
        target: /var/lib/mysql
      - type: bind
        source: ./config
        target: /config
    restart: always
