import itertools
import re
from collections import OrderedDict

import requests
from app.constants.css_constants import code_box_css
from app.projects.project import Project
from fastapi import APIRouter, Form, Request, Response
from fastapi.responses import HTMLResponse
from jinja2 import Environment
from ollama import GenerateResponse, generate

e_filter = Environment().filters["e"]


# HTMX powered logic to update a chat frontend
class AI_Project(Project):
    def __init__(self, name, description, icon_path, route_base):
        super().__init__(name, description, icon_path, route_base)
        self.is_local = True
        self.regex_progs = {
            "code_block": re.compile(r"```(\w+)(.*?)(```)", re.DOTALL),
        }
        self.__sanitizize_code_format = """
      <div class="{code_box_css}">
        <h1 class="text-2xl text-wrap">Generated Code Block in the {language} language:</h1>
        <pre class="text-wrap"><code>
          {generated_code}
         </code></pre>
      </div>"""

    def sanitize_response_code_escape(self, match: re.Match):
        language = match.group(1)
        generated_code = match.group(2)
        return self.__sanitizize_code_format.format(
            code_box_css=code_box_css, language=language, generated_code=generated_code
        )

    def sanitize_response(self, response: str):
        return self.regex_progs["code_block"].sub(
            self.sanitize_response_code_escape, response
        )

    def parse_template(self, request: Request):
        return self.templates.TemplateResponse(
            "projects/ai_project.html", {"request": request}
        )

    async def sendMessage(self, request: Request):
        if self.is_local:
            form = await request.form()
            messageInput = form["messageInput"]
            systemPrompt = form["systemPrompt"]
            context = ""
            variables = {"messageInput": messageInput, "context": context}

            fullPrompt = systemPrompt.format(**variables)

            response: GenerateResponse = generate(
                model="mistral-nemo", prompt=messageInput, system=systemPrompt
            )
            response = response["response"]
            # pre e-filter since I use safe output
            # e-filter everything so people can't manipulate AI output to dodge a parse. Everything gets filtered.
            # runs before sanitize response so HTML generated by AI is not escaped
            response = e_filter(response)
            response = self.sanitize_response(response)
        else:
            response = "Currently this application only runs on my local machine (my server can't handle the LLM it doesn't have a GPU). If you pull the code for this website you can use this tool on your own local to interact with ollama chat models"

        # or access fields directly from the response object
        return self.templates.TemplateResponse(
            "htmx_partials/chatMessage.html", {"request": request, "response": response}
        )


project = AI_Project(
    "AI Tool",
    "A simple tool I use to interact with ollama locally",
    "assets/img/Flanette.png",
    "/ai",
)
router = APIRouter()


# -- Map class methods to functions for router --
@router.get("/ai", response_class=HTMLResponse)
def ai_route(request: Request):
    return project.parse_template(request)


@router.post("/ai/send-message", response_class=HTMLResponse)
async def send_message_route(request: Request):
    return await project.sendMessage(request)
